# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'QiscusMeet'

target 'QiscusMeetExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#  pod 'QiscusMeet', '2.0.0.rc.1'
  pod 'QiscusMeet', :path => '../'
  pod 'Firebase/Analytics', '6.30.0'
  pod 'Firebase/Crashlytics', '6.30.0'
  pod 'Crashlytics'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  end
